### ISSUE TITLE
`yap` vs `pacur`

### ISSUE THREAD

**Issue by polarathene** [PackageFoundation/yap#52]
While looking for projects for packaging, I noticed that both `yap` and [`pacur`](https://github.com/pacur/pacur) have README with lots of the same content? It looks like `pacur` is the older project based on age and number of commits. Is `yap` a fork of `pacur`?

**EDIT:** I just noticed the README for `yap` has a "Credits" section at the end referencing the project, but not linking to it. There doesn't appear to be any description of how `yap` differs from `pacur`, or why it was created? Both seem to be actively maintained?

**Comment by Polpetta** [comment]
Hi @polarathene!

Sorry for replying so late. Yes this is a fork of `pacur`, we decided to hard fork it since we preferred to take the project and move it to a different direction. We also cited the original project in the "Credits" section since without `pacur` this project won't be possible in the first place.

If you have any suggestion to make or any idea in mind please don't hesitate to post in in the "Discussions" tab https://github.com/PackageFoundation/yap/discussions so we can take them in consideration :smile: 

Thanks for asking!
